import { Question } from './types';

export const module1Questions: Question[] = [
  {
    id: 1,
    moduleId: 'module-1',
    moduleNumber: 1,
    moduleTitle: 'Just Delegate It',
    scenario: 'A fintech startup integrates an autonomous agent to manage customer refund disputes under $150. During peak Black Friday traffic, the agent encounters ambiguous receipts where the merchant identity cannot be validated with 100% confidence. The lead engineer must configure the delegation boundary between full autonomy and human escalation.',
    question: 'According to the "Just Delegate It" framework regarding reversible vs. irreversible actions (One-Way Doors vs. Two-Way Doors), what is the most architecturally sound delegation boundary?',
    options: {
      A: 'Allow the agent to autonomously approve and disburse funds immediately because monetary loss under $150 is easily absorbed as operating expense.',
      B: 'Classify financial disbursement as an irreversible One-Way Door action; configure the agent to draft the decision and compute confidence scores, but require human cryptographic sign-off for release whenever merchant confidence is below the threshold.',
      C: 'Revoke agent access entirely and route all refund requests directly to tier-2 human operators during any high-volume event.',
      D: 'Force the agent into an infinite iterative loop prompting the customer repeatedly until confidence hits 100%.'
    },
    correctAnswer: 'B',
    rationale: 'Disbursing capital from an enterprise account is inherently a One-Way Door (irreversible or very costly to reclaim). Under modern agent delegation principles, high-consequence or irreversible side-effects must maintain Human-in-the-Loop (HITL) or Human-on-the-Loop (HOTL) sign-off whenever ambiguous conditions lower model confidence below predefined thresholds.',
    distractorBreakdown: {
      A: 'Treating real funds transfers as trivial creates unbounded financial drain and invites adversarial exploitation.',
      C: 'Total revocation creates human operational collapse under peak load, defeating the entire purpose of delegation.',
      D: 'Infinite agent prompting frustrates users and creates severe token cost runaway without resolving missing ground truth.'
    },
    urduSummary: 'Ghair-wapsi (irreversible / One-Way Door) faislon jese funds transfer me model ko sirf draft aur confidence calculate karne dein, aakhri sign-off insaan ke hath me rakhein.',
    corePrinciple: 'Irreversible Actions vs Two-Way Doors Boundary',
    difficulty: 'Hard'
  },
  {
    id: 2,
    moduleId: 'module-1',
    moduleNumber: 1,
    moduleTitle: 'Just Delegate It',
    scenario: 'An engineering team delegates code refactoring to an LLM agent. After two weeks, the tech lead realizes they spend 35 minutes reviewing, debugging subtle hallucinations, and verifying each 10-line PR generated by the agent—a task that previously took the engineer only 15 minutes to write manually from scratch.',
    question: 'Which fundamental paradox of AI delegation does this scenario illustrate, and how should it be mitigated?',
    options: {
      A: 'The Verification Asymmetry Paradox: Mitigation requires lowering the blast radius by forbidding the agent from touching code and restricting it solely to writing meeting summaries.',
      B: 'The Delegation Tax (Cognitive Overhead): When the cost of verifying an agent\'s output exceeds the cost of direct execution, delegation is negative-ROI; mitigation requires delegating only tasks where verification is mathematically or structurally cheaper than execution (e.g., test generation, linting, pure pure-function transformations with unit tests).',
      C: 'The Model Collapse Paradox: Mitigation requires retraining the foundation model on proprietary company commits.',
      D: 'The Context Drift Paradox: Mitigation requires increasing the LLM temperature so that the agent writes more creative code.'
    },
    correctAnswer: 'B',
    rationale: 'Delegation is economically viable only when verification cost is substantially lower than execution cost ($C_{verify} \\ll C_{execute}$). When an engineer must parse subtle logic flaws in unstructured agent code line-by-line, the cognitive load and time exceed manual authoring. Tasks must be constrained to formats where automated tests or rapid structural checks verify correctness instantly.',
    distractorBreakdown: {
      A: 'Relegating agents only to meeting summaries abandons engineering utility without understanding how to harness automated verification.',
      C: 'Fine-tuning does not solve the fundamental cognitive verification overhead of ambiguous refactoring.',
      D: 'Increasing temperature increases randomness and hallucination rate, compounding the verification burden.'
    },
    urduSummary: 'Jab AI ke kaam ko verify karna khud likhne se ziada mushkil ho jaye to yeh Negative-ROI delegation ban jata hai. AI ko aisi jagah delegate karein jahan test cases se automated verification foran ho sake.',
    corePrinciple: 'Verification Cost vs Execution Cost Asymmetry',
    difficulty: 'Hard'
  },
  {
    id: 3,
    moduleId: 'module-1',
    moduleNumber: 1,
    moduleTitle: 'Just Delegate It',
    scenario: 'A DevOps lead wants to delegate server incident triage to an autonomous agent. The agent has CLI access to the production Kubernetes cluster. The team defines a Level 2 vs Level 3 delegation policy.',
    question: 'What distinguishes a Level 2 (Directed Task Agent) from a Level 3 (Semi-Autonomous with Guardrails) agent in production delegation?',
    options: {
      A: 'Level 2 requires specifying exact shell commands for the agent to execute sequentially; Level 3 allows the agent to diagnose root cause, plan remediation steps, and execute read-only probes autonomously, but requires human approval before executing state-mutating actions (like pod restart or traffic rerouting).',
      B: 'Level 2 uses GPT-3.5 while Level 3 uses GPT-4o.',
      C: 'Level 2 agents cannot access APIs, whereas Level 3 agents have root SSH access without any logging.',
      D: 'Level 2 is completely deterministic bash scripts, while Level 3 operates without any system prompt.'
    },
    correctAnswer: 'A',
    rationale: 'In delegation autonomy taxonomies, Level 2 agents are strictly directed: the user specifies the precise sub-tasks and the agent carries out explicit mechanical instructions. Level 3 grants autonomous exploration, diagnostic synthesis, and non-destructive action within bounded guardrails, pausing at critical state-mutation boundaries for explicit human authorization.',
    distractorBreakdown: {
      B: 'Autonomy levels define governance frameworks and delegation boundaries, not proprietary model version tags.',
      C: 'Giving unlogged root SSH access is an egregious security violation, not a recognized autonomy standard.',
      D: 'Level 2 agents are LLM agents operating under narrow execution bounds, not purely hardcoded bash scripts.'
    },
    urduSummary: 'Level 2 me agent ko exact commands batani parti hain, jabke Level 3 me agent khud diagnose aur read-only check karta hai magar change karne se pehle approval leta hai.',
    corePrinciple: 'Levels of Autonomous Delegation (Level 2 vs Level 3)',
    difficulty: 'Hard'
  },
  {
    id: 4,
    moduleId: 'module-1',
    moduleNumber: 1,
    moduleTitle: 'Just Delegate It',
    scenario: 'An enterprise customer service agent is given full authority to issue store credits. A prompt-injected user tricks the agent into issuing a $5,000 credit. During the post-mortem, the VP asks why the blast radius was not capped.',
    question: 'In robust agent delegation architecture, which mechanism constitutes the primary defense for blast radius containment?',
    options: {
      A: 'Relying purely on system prompt admonitions such as "You must never issue more than $50 under any circumstance, I am serious".',
      B: 'Deterministic infrastructure-level policy enforcement (e.g., API gateway rate limits, hard-coded transactional caps, and scoped OAuth scopes) independent of the model\'s internal cognitive compliance.',
      C: 'Asking the user to promise they will not ask for more than $50 before opening the chat window.',
      D: 'Running three different LLMs in parallel and averaging the dollar amount they propose.'
    },
    correctAnswer: 'B',
    rationale: 'System prompts are probabilistic and vulnerable to jailbreaks or semantic evasion. True blast radius containment requires hard, deterministic, infrastructure-level boundaries: the tool API itself must reject any credit exceeding the policy cap ($50) or require multi-party cryptographic authorization, regardless of what the LLM instructs.',
    distractorBreakdown: {
      A: 'System prompt instructions can always be overridden via adversarial jailbreaks or semantic confusion.',
      C: 'User self-attestation provides zero security against malicious actors.',
      D: 'Consensus voting between probabilistic models still fails if the prompt injection exploits a universal systemic vulnerability.'
    },
    urduSummary: 'AI ke system prompt par bharosa na karein; API aur backend par hard limit ($50 cap) lagayein taake prompt injection ke bawajood bara nuqsan na ho.',
    corePrinciple: 'Deterministic Blast Radius Containment',
    difficulty: 'Extreme'
  },
  {
    id: 5,
    moduleId: 'module-1',
    moduleNumber: 1,
    moduleTitle: 'Just Delegate It',
    scenario: 'A product manager notices that team members oscillate between two pathological delegation extremes: either they micromanage the agent (editing every word of prompt output line-by-line) or they exercise blind trust (pushing uninspected multi-file agent commits directly to production).',
    question: 'To establish healthy delegation equilibrium, what must the team implement as a "Delegation Contract"?',
    options: {
      A: 'A signed HR document stating that developers will be fired if an agent introduces a bug.',
      B: 'Explicit Acceptance Criteria, Pre-flight Automated Invariant Checks, Defined Fallback Routes, and Measurable Escalation Triggers that govern the agent\'s operational envelope.',
      C: 'A policy enforcing that no AI agent can be used unless approved by the board of directors.',
      D: 'A daily meeting where developers read the entire prompt history aloud to the team.'
    },
    correctAnswer: 'B',
    rationale: 'A Delegation Contract is a formalized technical agreement between the human operator and the autonomous system: it specifies deterministic boundaries, automated acceptance criteria (e.g., test suites passing, schema validation), error budgets, and explicit signals that trigger human escalation instead of silent failure.',
    distractorBreakdown: {
      A: 'Punitive measures do not provide technical boundaries or solve cognitive calibration.',
      C: 'Excessive bureaucracy destroys development velocity without providing operational safety.',
      D: 'Reading prompt logs aloud is unscalable and fails to automate invariant checking.'
    },
    urduSummary: 'Delegation Contract ka matlab hai clear acceptance criteria, automated tests aur escalation rules tay karna taake na micromanagement ho aur na andha aitmaad.',
    corePrinciple: 'The Delegation Contract & Operational Envelope',
    difficulty: 'Hard'
  },
  {
    id: 6,
    moduleId: 'module-1',
    moduleNumber: 1,
    moduleTitle: 'Just Delegate It',
    scenario: 'An insurance firm delegates claim document parsing to an agent. For 90% of standard claims, the agent extracts medical codes with 99% accuracy. For 10% of claims with handwritten non-standard hospital forms, the agent\'s internal entropy spikes and accuracy drops to 62%.',
    question: 'Which delegation pattern ensures enterprise compliance and operational efficiency without overwhelming human specialists?',
    options: {
      A: 'Triage-and-Escalate routing: The agent processes high-confidence claims end-to-end, while claims with token logit entropy exceeding a calibrated threshold or missing checksums are automatically diverted to specialized human reviewers.',
      B: 'Have the agent guess the most common medical code whenever handwriting is illegible to maintain a 100% automated throughput KPI.',
      C: 'Send all 100% of claims to human specialists and have the agent merely email the PDF as an attachment.',
      D: 'Lower the model temperature to 0.0001, which mathematically guarantees that handwritten forms will be parsed correctly.'
    },
    correctAnswer: 'A',
    rationale: 'Confidence-based automated triage (selective routing) delegates the bulk of standard, high-confidence processing to the agent while reserving expensive human cognitive capacity exclusively for the long-tail edge cases where the model flags high uncertainty or low semantic confidence.',
    distractorBreakdown: {
      B: 'Fabricating medical codes violates regulatory compliance and legal statutes.',
      C: 'Routing 100% to humans discards the 90% efficiency gain on standard claims.',
      D: 'Zero temperature does not invent missing visual resolution or eliminate handwriting ambiguity; it merely makes hallucinations deterministic.'
    },
    urduSummary: 'Asan aur high-confidence claims AI handle kare, jabke mushkil aur ambiguous claims automatically human specialist ko escalate ho jayein.',
    corePrinciple: 'Confidence-Based Selective Routing & Human-on-the-Loop',
    difficulty: 'Hard'
  },
  {
    id: 7,
    moduleId: 'module-1',
    moduleNumber: 1,
    moduleTitle: 'Just Delegate It',
    scenario: 'A marketing team delegates social media publishing to an autonomous agent. The agent generates copy, selects hashtags, and publishes posts directly to 500,000 followers. One morning, the agent generates an offensive cultural misinterpretation due to an out-of-context news trend.',
    question: 'What governance flaw was committed during the delegation design?',
    options: {
      A: 'Using an LLM without fine-tuning it on the complete history of global humor.',
      B: 'Treating a public-facing, brand-critical broadcast as a Human-Out-of-the-Loop (HOOTL) automated task rather than a Human-in-the-Loop (HITL) staged draft workflow.',
      C: 'Failing to include the word "polite" in the system prompt.',
      D: 'Not allowing the agent to post 10 times more frequently to drown out negative feedback.'
    },
    correctAnswer: 'B',
    rationale: 'Public broadcasting to large audiences carries extreme asymmetric reputational risk (high blast radius). Even if generation is automated, final publishing should be a staged two-phase commit where an authorized human editor approves the staged post before public broadcast.',
    distractorBreakdown: {
      A: 'Fine-tuning does not guarantee zero cultural tone-deafness in real-time evolving global events.',
      C: 'Adjectives like "polite" in prompts do not prevent complex cultural or contextual misinterpretations.',
      D: 'Increasing posting volume multiplies reputational damage exponentially.'
    },
    urduSummary: 'Public social media broadcast jesi sensitive cheezon me AI ko direct posting ka ikhtiyar na dein; draft AI banaye magar publish insaan kare.',
    corePrinciple: 'Human-in-the-Loop for Asymmetric Reputational Risk',
    difficulty: 'Hard'
  },
  {
    id: 8,
    moduleId: 'module-1',
    moduleNumber: 1,
    moduleTitle: 'Just Delegate It',
    scenario: 'A software company delegates internal database migrations to an AI agent. The agent is tasked with modifying SQL schemas across 40 microservices based on high-level feature requirements.',
    question: 'When delegating tasks with systemic structural dependencies, which principle prevents cascading architecture degradation?',
    options: {
      A: 'Spec-first bounded delegation with dry-run verification: The agent must produce a deterministic migration plan and pass automated schema diff simulations in a sandbox before applying changes to staging environments.',
      B: 'Granting the agent direct production DB admin credentials so it can fix issues on the fly if a migration fails.',
      C: 'Instructing the agent to skip foreign key constraints so that queries run faster.',
      D: 'Prompting the agent to rewrite the entire database engine in Rust if migrations take too long.'
    },
    correctAnswer: 'A',
    rationale: 'Delegation of systemic changes requires spec-first boundaries: the agent produces declarative migration specifications, verified through deterministic dry-run simulations and automated invariant checkers before any environment mutation occurs.',
    distractorBreakdown: {
      B: 'Direct production admin access exposes the database to irreversible data corruption.',
      C: 'Removing foreign key constraints destroys relational integrity and creates catastrophic data drift.',
      D: 'Rewriting the database engine is an absurd, ungrounded hallucination that derails the assigned task.'
    },
    urduSummary: 'Database migrations jese ahem kamo me agent ko pehle sandbox me dry-run plan aur schema diff verify karwana zaroori hai.',
    corePrinciple: 'Dry-Run Verification in Systemic Delegation',
    difficulty: 'Hard'
  },
  {
    id: 9,
    moduleId: 'module-1',
    moduleNumber: 1,
    moduleTitle: 'Just Delegate It',
    scenario: 'An architect reviews an agent pipeline where Agent A creates research briefs, passes them to Agent B who writes code, and Agent B passes output to Agent C who deploys it. When an outage occurs, no engineer can explain which agent made the faulty assumption or why.',
    question: 'Which delegation flaw caused this diagnostic blindness?',
    options: {
      A: 'Using three agents instead of one monolithic 1-million-token prompt.',
      B: 'Lack of immutable provenance logging and state attribution: Each delegating hop must log input artifacts, explicit decision rationale, and tool execution signatures.',
      C: 'The agents were using Python instead of Go.',
      D: 'The agents did not send a Slack notification saying "I did it".'
    },
    correctAnswer: 'B',
    rationale: 'In multi-agent delegation chains, accountability collapses unless each hop maintains an immutable audit trail: tracking the exact input state, intermediate reasoning trace, delegated sub-goal, and verified exit state. Without provenance logging, post-incident root cause analysis becomes impossible.',
    distractorBreakdown: {
      A: 'Monolithic massive prompts introduce prompt saturation, hallucination, and degraded reasoning.',
      C: 'The programming language of the runtime has no bearing on systemic delegation provenance.',
      D: 'Informal chat notifications lack machine-readable trace telemetry and structured error contexts.'
    },
    urduSummary: 'Har agent ke darmiyan input, reasoning trace aur tool output ka mukammal record (provenance logging) hona chahiye taake kharabiyon ka pata lag sake.',
    corePrinciple: 'Immutable Provenance & Multi-Agent Attribution',
    difficulty: 'Extreme'
  },
  {
    id: 10,
    moduleId: 'module-1',
    moduleNumber: 1,
    moduleTitle: 'Just Delegate It',
    scenario: 'A CEO instructs the engineering department to "delegate everything possible to agents by next month to achieve 10x developer output". Within three weeks, repository merge conflicts spike by 400%, code review queues are hopelessly clogged with 2,000-line AI PRs, and team morale plummets.',
    question: 'What core organizational lesson from the "Just Delegate It" framework did executive leadership violate?',
    options: {
      A: 'Delegation is not a zero-cost abstraction; velocity without rigorous verification harnesses creates a "WIP (Work-In-Progress) Inventory Trap" where cognitive review bottlenecks paralyze the organization.',
      B: 'The company should have purchased more expensive GPU subscriptions for every engineer.',
      C: 'Agents should be allowed to review and merge their own PRs directly to main without any human involvement.',
      D: 'Engineers are obsolete and the CEO should manage the agents directly.'
    },
    correctAnswer: 'A',
    rationale: 'Generating artifacts with AI is virtually free, but reviewing and validating them requires scarce human cognitive bandwidth. Unbounded delegation without automated verification harnesses simply moves the bottleneck from authoring to review, creating an unmanageable inventory of unverified code that clogs the engineering pipeline.',
    distractorBreakdown: {
      B: 'Faster hardware exacerbates the review backlog by generating more unreviewed code even faster.',
      C: 'Allowing unverified agents to merge into production creates catastrophic system destabilization and security vulnerabilities.',
      D: 'Human engineering judgment remains essential for architecture, specification, and safety bounds.'
    },
    urduSummary: 'Code generate karna aasan hai magar usay review karna mushkil. Baghair automated tests aur limits ke andhadhund delegation se team ka waqt zaya hota hai.',
    corePrinciple: 'The Review Bottleneck & WIP Inventory Trap',
    difficulty: 'Hard'
  }
];
